### ISSUE TITLE
How to update easily?

### ISSUE THREAD

**Issue by schmjop** [702573N/Obsidian-Tasks-Timeline#1]
Hi @702573N,
I just found Taskido and I am already loving it! I was able replace some basic Tasks queries as this custom view already contains so much information, thank you!

Since there are frequent releases in this repo, is there an easy way to update this custom view? Having a community plugin would be great! Same goes for your calendar view.

Thank you.

**Comment by 702573N** [comment]
Hi @schmjop
First of all, thank you very much for these kind words. It gives me great pleasure to help people get a better overview of their tasks with my views. Of course, a real plugin would be a better solution. Unfortunately, I am not a programmer and have therefore failed several times in developing a plugin. Maybe I will try again someday, but it's all in the stars. Nevertheless, the way via a Dataview view also offers some advantages. Every user can adapt this script himself (provided he has some understanding of Javascript and CSS) without having to hope or wait for the plug-in programmer to implement it every time. Perhaps I will also find a way in the future to use Dataview to better access the vault or the files in it. Then the file content of view.js and view.css could perhaps be updated automatically after confirmation by the user. But that too is still in the stars. I am very sorry not to be able to give you better feedback. All the best.

**Comment by schmjop** [comment]
Thank you for you in-depth reponse. I completely understand and I agree that the current approach also has its benefits. Thanks again for the pretty and useful task views.
