### ISSUE TITLE
how to toggle the task status in the timeline panel?

### ISSUE THREAD

**Issue by wuzhen97** [702573N/Obsidian-Tasks-Timeline#12]
hello，does it support setting the task status to complete in the timeline panel ?

**Comment by 702573N** [comment]
Unfortunately not. I'm working on this in future. Stay tuned.

**Comment by wuzhen97** [comment]
Thank you. I'm looking forward to it

**Comment by 702573N** [comment]
Please download the latest version [1.1.5](https://github.com/702573N/Obsidian-Tasks-Timeline/archive/refs/heads/main.zip)!
