### ISSUE TITLE
reminder plugin support

### ISSUE THREAD

**Issue by wuzhen97** [702573N/Obsidian-Tasks-Timeline#13]
Hello，do you know the plugin “[obsidian-reminder](https://github.com/uphy/obsidian-reminder)”?
It can enhance the Tasks plugin and add a reminder for each task：

![image](https://user-images.githubusercontent.com/61906420/212510535-fa986d33-5d29-400e-9f51-745f45c0f072.png)

![image](https://user-images.githubusercontent.com/61906420/212510980-7cdc25bd-dda3-4ba0-8bd9-45a747c616c9.png)

thanks~

**Comment by webrunneronSun** [comment]
OK, will try it. thanks for the remind.

**Comment by 702573N** [comment]
I know the plugin, but it is frustrating that so far it only runs on the desktop, but not on mobile devices. I can detect the reminders using a regex and remove them from the task text if that is their concern.

**Comment by wuzhen97** [comment]
> I know the plugin, but it is frustrating that so far it only runs on the desktop, but not on mobile devices. I can detect the reminders using a regex and remove them from the task text if that is their concern.

Hello, this plugin support the mobile now, except System notification. You can see from [here](https://github.com/uphy/obsidian-reminder#faq).

**Comment by 702573N** [comment]
The webpage says something else...
<img width="825" alt="Bildschirm­foto 2023-01-15 um 07 15 56" src="https://user-images.githubusercontent.com/59178587/212525958-3a528a0c-46f6-46b4-bdef-3c679da8a216.png">

**Comment by 702573N** [comment]
That's the thing... it is precisely for these system notifications that the reminder is needed

**Comment by 702573N** [comment]
Regardless of the reminder syntax in the task text, are there any problems with the reminder plugin in combination with the timeline?

**Comment by wuzhen97** [comment]
> Regardless of the reminder syntax in the task text, are there any problems with the reminder plugin in combination with the timeline?

all well ，thanks

**Comment by 702573N** [comment]
- Reminders are now cutted out from task description text.
- ToDo counter now includes starting tasks 

[view.js](https://github.com/702573N/Obsidian-Tasks-Timeline/blob/main/Taskido/view.js)
[view.css](https://github.com/702573N/Obsidian-Tasks-Timeline/blob/main/Taskido/view.css)

**Comment by wuzhen97** [comment]
thank you
