### ISSUE TITLE
the info box “To Do”  is always zero

### ISSUE THREAD

**Issue by wuzhen97** [702573N/Obsidian-Tasks-Timeline#14]
![image](https://user-images.githubusercontent.com/61906420/212519632-4f8405ec-bf24-4f2d-8953-ffc5ab69142d.png)

**Comment by wuzhen97** [comment]
this may because that the start time is before due time:

**Comment by 702573N** [comment]
You are right, the same dates in start date and due date cause problems. I have to fix that. Thank you for pointing this out.

**Comment by 702573N** [comment]
Does it make sense to assign the same date to the start date and the due date? In such a case, I would actually only assign the due date.

**Comment by wuzhen97** [comment]
Oh sorry, I misled you. I want to say that this is due to the existence of the start date, not the date：

![image](https://user-images.githubusercontent.com/61906420/212525035-a06b8360-b438-41ac-b00e-77dd77f6034e.png)

**Comment by wuzhen97** [comment]
I think as long as a task is between the start and due, it can be regarded as To Do. thanks~

**Comment by 702573N** [comment]
I have tried to fix it and in addition I have included the tasks in process in the todo counter (task starting before today and due is after today). Please test!

[view.js](https://github.com/702573N/Obsidian-Tasks-Timeline/blob/main/Taskido/view.js)
[view.css](https://github.com/702573N/Obsidian-Tasks-Timeline/blob/main/Taskido/view.css)

Both files must be replaced for this!

**Comment by wuzhen97** [comment]
> I have tried to fix it and in addition I have included the tasks in process in the todo counter (task starting before today and due is after today). Please test!
> 
> [view.js](https://github.com/702573N/Obsidian-Tasks-Timeline/blob/main/Taskido/view.js) [view.css](https://github.com/702573N/Obsidian-Tasks-Timeline/blob/main/Taskido/view.css)
> 
> Both files must be replaced for this!

thanks for your hot fix！all well done，but you might ignore the start time，it doesnt work for the start day：

![image](https://user-images.githubusercontent.com/61906420/212526610-de20fdca-3e0e-41c8-b980-7d6c85b281e8.png)

**Comment by 702573N** [comment]
- Reminders are now cutted out from task description text.
- ToDo counter now includes starting tasks 

[view.js](https://github.com/702573N/Obsidian-Tasks-Timeline/blob/main/Taskido/view.js)
[view.css](https://github.com/702573N/Obsidian-Tasks-Timeline/blob/main/Taskido/view.css)

**Comment by wuzhen97** [comment]
Thank you for your efforts
