### ISSUE TITLE
can i use the link in everts?

### ISSUE THREAD

**Issue by webrunneronSun** [702573N/Obsidian-Tasks-Timeline#15]
as shown below, without the double square brackets, these works well. Just wonder, is it possible to use a link for the date of an events?

![image](https://user-images.githubusercontent.com/119090113/212540376-0cd366d3-1d9e-4896-a113-996e81bb0271.png)

**Comment by 702573N** [comment]
I'm sorry but the timeline is programmed as a helper tool for using Task-Plugin and/or Dataview-Plugin. Daily notes are supported too.


You can include links to your notes inside task description. These are also clickable inside the timeline. But you can't combine a due-date with a link.

**Comment by webrunneronSun** [comment]
this is a meaningless request. thanks for a quick response.
