### ISSUE TITLE
Can the brackets of internal links be hidden like the calendar view？

### ISSUE THREAD

**Issue by wuzhen97** [702573N/Obsidian-Tasks-Timeline#16]
Sorry to bother you again, I remember that the brackets of links can be hidden in the previous version, but not in the latest version?

![image](https://user-images.githubusercontent.com/61906420/212541370-36d882f8-3ded-4301-8a10-dc06ad863172.png)

**Comment by 702573N** [comment]
There is a bug in the latest version. I have fixed this.
[Download: view.js](https://github.com/702573N/Obsidian-Tasks-Timeline/blob/main/Taskido/view.js)

**Comment by wuzhen97** [comment]
thanks~
