### ISSUE TITLE
why my note appears in the timeline？

### ISSUE THREAD

**Issue by wuzhen97** [702573N/Obsidian-Tasks-Timeline#17]
![image](https://user-images.githubusercontent.com/61906420/212596318-207e563e-3b5c-4f3a-b86f-231187dad241.png)

Hello, why are these contents in my timeline? What does this symbol mean? It seems that one of my previous checkboxes contains an internal link to that notes, and then they appear here. 

Thank you very much for your efforts~

**Comment by 702573N** [comment]
You can pin special notes to your timeline based on the creation date by using the star function in Obsidian
