### ISSUE TITLE
Display of links

### ISSUE THREAD

**Issue by gjjg007** [702573N/Obsidian-Tasks-Timeline#2]
For tasks that have embedded URL links, the timeline just shows the URL instead of the description.  eg. Timeline displays this:  

![image](https://user-images.githubusercontent.com/121992117/210687491-dc2e8de1-12be-48b2-862f-8d30a3a61de4.png)

when it should display this: 

![image](https://user-images.githubusercontent.com/121992117/210687517-3e0b2ddb-2194-426c-98d3-e829be5e9f4d.png)

**Comment by 702573N** [comment]
Please note the new version 1.0.3

**Comment by gjjg007** [comment]
Nicely done, Thanks!
