### ISSUE TITLE
Display week/month calendar based on specific file name

### ISSUE THREAD

**Issue by foenixp** [702573N/Obsidian-Tasks-Timeline#22]
Hi,
This is a great snippet I have been dreaming of. Thank you so much for creating it!
I wonder if this feature could be done: I want to add the weekly calendar view to my weekly note (my weekly note named 2023-W03), and the calendar would display the week of that note, instead of the current week. For example, right now is Week 3, so when I open Week 1 weekly note, the calendar should show Week 1 tasks calendar. But right now it always shows the current Week 3 no matter where I put the dataviewjs code.

**Comment by 702573N** [comment]
Unfortunately, I don't understand her request as it sounds more like the Obsidian Tasks calendar than the Obsidian Tasks timeline. Or do they want a custom week implemented as a starting point for the timeline? If this is their request, then I'm afraid I'll have to disappoint them and would rather advise the use of the Obsidian Task Calendar snippet.
