### ISSUE TITLE
[Feature Request] Invert sorting in listview

### ISSUE THREAD

**Issue by ragundo** [702573N/Obsidian-Tasks-Timeline#23]
Hi there.
I love your script. Very very useful. I use exclusively the listview, not the calendar.

But it drives me crazy that past entries are first and current (and future ones) are bottom.  
Would it be too complicated to provide an option for inverting the view? Past entries bottom, recent entries top.

Thanks

**Comment by 702573N** [comment]
[v1.1.6 released](https://github.com/702573N/Obsidian-Tasks-Timeline/releases/tag/1.1.6)
