### ISSUE TITLE
how to use taskOrder？

### ISSUE THREAD

**Issue by wuzhen97** [702573N/Obsidian-Tasks-Timeline#24]
hello，please tell me how to use the taskOrder field to order the tasks？I try to use it as follows，but it doesn't work：

![image](https://user-images.githubusercontent.com/61906420/213843354-72cc181b-103b-41da-87bf-d04c54dc7e3e.png)

![image](https://user-images.githubusercontent.com/61906420/213843382-c6bc5dd6-5c56-4e23-97e1-2e9ac791e41c.png)

**Comment by 702573N** [comment]
Hi,
the `taskOrder` parameter isn't official at the moment. You probably stumbled upon it by examining my code. You have used it completely correctly, however, as just mentioned, this function has not yet been completed. Please download the latest view.js file. This should fix the sorting error you are experiencing.
