### ISSUE TITLE
Improvement suggestion: do not repeat file name in the timeline

### ISSUE THREAD

**Issue by busera** [702573N/Obsidian-Tasks-Timeline#28]
Hello,
For the overdue tasks I would recommend not to repeat the file name as separated (please see screenshot). This would reduce the list length and could improve the readability.

Cheers
![image](https://user-images.githubusercontent.com/20663020/215326251-774385ab-9f62-4b6e-8587-7e150345705c.jpeg)

**Comment by 702573N** [comment]
This feature request exists here #11

**Comment by busera** [comment]
Thanks for the reference.
