### ISSUE TITLE
Support showing Dataview tasks

### ISSUE THREAD

**Issue by wenlzhang** [702573N/Obsidian-Tasks-Timeline#3]
While Tasks Calendar can display tasks annotated with Dataview inline fields, Tasks Timeline does not seem to support this well. I am using the same query for looking for desired tasks. However, tasks like `- [ ] Task [due::2023-01-06]` shows up in Tasks Calendar but does not show up in Tasks Timeline.

**Comment by 702573N** [comment]
For the timeline, the keys (due, start, scheduled) are stored in a separate object 'happens'. This enables me to handle the dates better. However, this now had the consequence that the entries of inline fields are attributed to the task object in the context of Dataview, but have no effect in the timeline. I have now programmed an additional getMeta loop for the tasks with Dataview inline fields. I hope that everything works again with this.

**Comment by 702573N** [comment]
Take a look at the new version [1.0.5](https://github.com/702573N/Obsidian-Tasks-Timeline/releases/tag/1.0.5)
