### ISSUE TITLE
Task as first heading rather than note filename

### ISSUE THREAD

**Issue by mrsjbwells** [702573N/Obsidian-Tasks-Timeline#31]
Firstly, fantastic job .. this has been a game changer for me. Is it possible to show the task heading as the main heading rather than the note filename.

**Comment by 702573N** [comment]
Is it really enough to display only the header, or would a combination of both (if a header exists) be better?

Such as:
filename > header

**Comment by mrsjbwells** [comment]
thanks for responding so quickly. in the pic below, it shows filename first then repeat then task. is it possible that i can flip the filename and task as i list multiple tasks on one filename and add time in front of tasks to order them.

![Screenshot_20230205_094545_Obsidian.jpg](https://user-images.githubusercontent.com/19353477/216792879-0333f175-7082-4f8d-87bf-61e729542ab2.jpg)

**Comment by 702573N** [comment]
v1.1.7 released

**Comment by mrsjbwells** [comment]
thankyou so much ... it works and is exactly what i need ... looks great on the android screen too

------- Original Message -------
