### ISSUE TITLE
Hide unplanned tasks by default 

### ISSUE THREAD

**Issue by apricot13** [702573N/Obsidian-Tasks-Timeline#32]
I'm having a little trouble finding the right combination of settings for the functionality I need, essentially I want to replicate the functionality of the 'noDailyNote' flag in the [Tasks Calendar](https://github.com/702573N/Obsidian-Tasks-Calendar) script and  hide unplanned tasks by default 

I figured I could do this by setting the options to prefilter `todoFilter overdueFilter` which didn't work. I tried `counterAction` from [this comment](https://github.com/702573N/Obsidian-Tasks-Timeline/issues/21#issuecomment-1385361174) but that didn't help either. (I also tried removing the `forward` and `dailyNoteFolder` options as well)

Could you point me in the right direction? 

```js
await dv.view("taskido", {pages: "", options: "noDone noYear todoFilter overdueFilter", dailyNoteFolder: "daily", forward: true})
```

```js
await dv.view("taskido", {pages: "", options: "noDone noYear todoFilter overdueFilter", dailyNoteFolder: "daily", forward: true, counterAction: "focus"})
```

**Comment by 702573N** [comment]
v1.2.1 released!

**Comment by apricot13** [comment]
Thank you @702573N!
