### ISSUE TITLE
[Bug report] Strange block covers the `timeline.stripe`.

### ISSUE THREAD

**Issue by Leonezz** [702573N/Obsidian-Tasks-Timeline#37]
Hi, I like what you designed in this plugin, especially some beautiful details like the stripe (vertical line) below the checkbox icon.

But I am facing a problem with the style of the stripe, like the screen shots blow, there is a strage block showing in front and it covers the strip, which makes it looks bad.

![In drak mode](https://user-images.githubusercontent.com/33564074/219944363-4f4cb481-f9b9-4658-bf84-6d8c2e83b53b.png)

![In light mode](https://user-images.githubusercontent.com/33564074/219944384-79960146-681f-4437-9467-a50e4cbd4400.png)

I checked the style sheet with the developer tools and find it is caused by a `.timeline::after` style, but I am unable to find this style snippet in the `view.css`.

By the way, not sure have you read the issue I opened for a wrapper plugin (https://github.com/702573N/Obsidian-Tasks-Calendar/issues/57#issue-1587938228), please check it out if it may, looking forward to talk to you about it.

**Comment by 702573N** [comment]
Apparently there is a CSS conflict with them which displays the line of the timeline (stripe pseudo :after element) incorrectly. This could be caused by a theme or some third party plugin. I have removed the pseudo element completely and solved the line display differently. Hopefully this will solve this display problem for you.

**Comment by Leonezz** [comment]
You are right, turns out another plugin called Timelines conflicts with this script, I guess there is also a timeline class name. Thanks for your respond and my problem is solved.
