### ISSUE TITLE
Undesired notes would display in the timeline view

### ISSUE THREAD

**Issue by wenlzhang** [702573N/Obsidian-Tasks-Timeline#4]
Sometimes, notes that do not satisfy the Dataview queries would display in the timeline view. For example, I have the following notes that should not display:

- Notes with no tasks at all
- Notes with tasks but without the desired tags

For example, one note that should not display is as follows. As can be seen, the icon might correspond with a note, which is not the same as the icon for tasks:
<img width="653" alt="image" src="https://user-images.githubusercontent.com/44930227/211143462-4a21d626-2b0d-40e7-8f58-06afbc35ea17.png">

**Comment by 702573N** [comment]
Have you noticed, that your starred notes are pinned to the timeline by default? If you don't like that feature you can disable it by entering `starred: false`

**Comment by wenlzhang** [comment]
> Have you noticed, that your starred notes are pinned to the timeline by default?

Aha, didn't realize that. Maybe that's because I haven't used the starred notes feature of Obsidian for a very long time...

I now have these options `overdueTasksToday: true, starred: false, options: "noAdd noPriority todoFocus"`. However, the starred notes would not be hidden.

**Comment by 702573N** [comment]
Please download [view.js](https://github.com/702573N/Obsidian-Tasks-Timeline/blob/main/Taskido/view.js) and check for further bugs!

**Comment by wenlzhang** [comment]
Thanks! It works now.
