### ISSUE TITLE
Recurring tasks not displaying

### ISSUE THREAD

**Issue by joaonunatingscode** [702573N/Obsidian-Tasks-Timeline#47]
I have a 'every weekday' task which is not being displayed in the today (today being a weekday) area.

In your README.md the top image shows recurring/repeating tasks showing correctly.

**Comment by simonmeggle** [comment]
I can confirm this. Recurring tasks are not showing.

**Comment by joaonunatingscode** [comment]
It's now showing for me. You should read the Tasks plugin docs on [recurring tasks.](https://obsidian-tasks-group.github.io/obsidian-tasks/getting-started/recurring-tasks/)

Basically a recurring task should have a 'due' date in order to show in the Timeline (and _happens_ filter).
So to fix this issue specifically I just added 'due tomorrow' in the Task editor UI. The recurrence will update the due date accordingly.

Also refer to [this](https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/1803) discussion with the Tasks plugin maintainer.
