### ISSUE TITLE
Overdue Dataview tasks would not display on today

### ISSUE THREAD

**Issue by wenlzhang** [702573N/Obsidian-Tasks-Timeline#5]
For overdue Dataview tasks like `- [ ] Task [due::2023-01-01]`, they would not display on today when `overdueTasksToday: true` is used.

**Comment by 702573N** [comment]
Please download [view.js](https://github.com/702573N/Obsidian-Tasks-Timeline/blob/main/Taskido/view.js) and check for further bugs!

**Comment by wenlzhang** [comment]
Thanks! It works now.
