### ISSUE TITLE
the rule about filter task

### ISSUE THREAD

**Issue by Ben9706** [702573N/Obsidian-Tasks-Timeline#53]
I really like this plugin. There is just a confusion when using it and I would appreciate an answer!

Currently, only tasks in DailyNote and Inbox are recognised, tasks in other folders don't appear without a date specified.
For example, task1 that appears in the picture is under DailyNote, while task2 in Project/Note1 does not appear in unplanned.

What should I do to show task2 her

My script is set up as shown.

Thank you very much for making this plugin!

<img width="1428" alt="截屏2023-07-13 11 26 09" src="https://github.com/702573N/Obsidian-Tasks-Timeline/assets/47425245/d505c645-0f95-4f6e-b581-4a7a5a67ad63">

<img width="758" alt="截屏2023-07-13 11 32 04" src="https://github.com/702573N/Obsidian-Tasks-Timeline/assets/47425245/652fa8f9-182f-40da-b67f-a1be5c079c2f">

**Comment by ablizno** [comment]
You need to use the option: unplannedFilter to add tasks without a date to your timeline.
