### ISSUE TITLE
Support hiding note names

### ISSUE THREAD

**Issue by wenlzhang** [702573N/Obsidian-Tasks-Timeline#6]
In my use case, it often happens that one note would only contain one task to show in the Timeline view. In this case, showing the note names can take too much space. Therefore, it would be great if there can be an option to hide note names where the tasks comes from.

**Comment by wenlzhang** [comment]
The note names can be displayed in a way similar to Tasks Calendar, where they only display when hovering on the tasks.

**Comment by 702573N** [comment]
Added two new options to the latest [view.css](https://github.com/702573N/Obsidian-Tasks-Timeline/blob/main/Taskido/view.css)

- `noFile` to hide filenames
- `noInfo` to hide tag, priority and recurrence line

Added show title on hovering task [view.js](https://github.com/702573N/Obsidian-Tasks-Timeline/blob/main/Taskido/view.js)

**Comment by 702573N** [comment]
Unfortunately, I can't recreate that in my Vault. Please close Obsidian completely once (also in the background) and reopen the app!
