### ISSUE TITLE
Strange results with the option noFile

### ISSUE THREAD

**Issue by wenlzhang** [702573N/Obsidian-Tasks-Timeline#7]
With the css and js files from https://github.com/702573N/Obsidian-Tasks-Timeline/issues/6, I get the following results with the options `overdueTasksToday: true, starred: false, options: "noFile noAdd"`. I got similar results even when removing `noFile` from the option.

<img width="463" alt="image" src="https://user-images.githubusercontent.com/44930227/211160528-3a1cb4c1-cb76-42d0-82f6-f25b1f3f950a.png">

**Comment by wenlzhang** [comment]
The result is the same when I use the js and css files from the master branch of the repo.

**Comment by 702573N** [comment]
Unfortunately, I can't recreate that in my Vault. Please close Obsidian completely once (also in the background) and reopen the app!

**Comment by wenlzhang** [comment]
> Please close Obsidian completely once (also in the background) and reopen the app!

I did this several times. Unfortunately, I had the same issue in two of my vaults.

**Comment by 702573N** [comment]
When this result now appears when option: "" is completely empty, then i suspect that your view.js file is corrupted or incomplete.

**Comment by wenlzhang** [comment]
I tested with `, options: ""`, and still see the same error. Regarding the `view.js` file, I directly downloaded it from the repo and did not make any modifications.

**Comment by 702573N** [comment]
[Obsidian-Tasks-Timeline-1.0.5](https://github.com/702573N/Obsidian-Tasks-Timeline/releases/download/1.0.5/Obsidian-Tasks-Timeline-1.0.5.zip)

Nevertheless, something must be different in your vault. I don't see any strange characters. Please send me your complete dv.view() line! Also, have you added any new notes or tasks since this morning that are different from the other tasks? Have you installed any new plugins or changed any settings in Obsidian?
Furthermore, please download v1.0.5 from the above link, unpack, replace your complete Taskido folder with the unpacked one!

**Comment by wenlzhang** [comment]
The code is as follows:

```dataviewjs
await dv.view("Taskido", {pages: "dv.pages().file.where(f=>f.tags.includes('#ToDo')).tasks.where(t => !(t.status == '-' || t.status == '/' || t.status == 'x' || t.status == '>'))", overdueTasksToday: true, starred: false, options: ""})
```

> Also, have you added any new notes or tasks since this morning that are different from the other tasks? Have you installed any new plugins or changed any settings in Obsidian?

No, I didn't do any of this since this morning.

Version 1.0.5 works fine as before.

**Comment by 702573N** [comment]
Please send a demo.md file containing task/s which return such a strange string!

**Comment by 702573N** [comment]
Please try the latest versions of view.js + view.css!!!

[Download ZIP-File here!](https://github.com/702573N/Obsidian-Tasks-Timeline/archive/refs/heads/main.zip)

**Comment by wenlzhang** [comment]
After further tests, it turns out that it could be related to how the tasks are created. For example, there are issues with the following tasks:

The tasks:
```
- [ ] Read a book [created::2023-01-01] #ToDo [ c:: #DVTC4R ] [p::1] #CategoryReading ⏫ 🔁 every day 📅 2023-01-09
- [ ] Test another task 📝 2023-01-01T12:00 [sf::1] [created::2023-01-01] #ToDo [ c:: #DVTC1R ] [p::2] [i::2] [due::2023-01-31]
```

The query:
```dataviewjs
await dv.view("Taskido", {pages: "dv.pages().file.where(f=>f.tags.includes('#ToDo')).tasks.where(t => !(t.status == '-' || t.status == '/' || t.status == 'x' || t.status == '>'))", overdueTasksToday: true, options: ""})
```

The result:
<img width="659" alt="image" src="https://user-images.githubusercontent.com/44930227/211188916-5951ccb2-f180-4b9f-ba4d-ff9d2d38e76f.png">

**Comment by 702573N** [comment]
Thank you very much for sending the two demo tasks in markdown, really helpful. Crazy management system you have build. I hope that all bugs are fixed now. Take a look:

[view.js](https://github.com/702573N/Obsidian-Tasks-Timeline/blob/main/Taskido/view.js)

**Comment by 702573N** [comment]
Attention: The latest js/css implement a global change in hiding starred files. The parameter `starred: false` is gone and replaced by the new option `options: "noStar"`.

**Comment by wenlzhang** [comment]
> Thank you very much for sending the two demo tasks in markdown, really helpful.

Thanks for the fix! It works for most of my tasks now!

On the other hand, it appears that there are still some issues if note links are included in the task text, e.g. `-[ ] #GTDWaitingFor the result on [[2022-09-30]] 📝 2023-01-01T12:00 [due::2022-11-30]`.

> Crazy management system you have build.

Haha. The main reason for this is that I would like to have more control on the tasks. For instance, I would like to use Dataview to group and sort tasks based on category, priority, importance, etc. Since I can use text expanders like espanso to quickly add those properties, it was not a problem for me.

**Comment by 702573N** [comment]
Hope we got it!

[view.js](https://github.com/702573N/Obsidian-Tasks-Timeline/blob/main/Taskido/view.js)

**Comment by wenlzhang** [comment]
Great! It works perfectly now!
